#!/bin/sh

set -e

DEB_HOST_MULTIARCH=aarch64-linux-gnu
THIS_PACKAGE=mali-400-fbdev-driver
THIS_SCRIPT=prerm

case "$1" in
  remove)
  # Use alternatives to make it easier to switch between Mali and 3rd party modules
  update-alternatives --remove ${DEB_HOST_MULTIARCH}_egl_conf /usr/lib/${DEB_HOST_MULTIARCH}/mali-egl/ld.so.conf

  # explicit ldconfig due to alternatives
  ldconfig

esac

#DEBHELPER#

exit 0
